language: julia
os:
- linux
julia:
- 1.2
notifications:
  email: false
git:
  depth: 99999999
  submodules: false
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
before_script:
- julia -e 'using Pkg; Pkg.add("BinaryBuilder")'
script:
- julia build_tarballs.jl --verbose
deploy:
    provider: releases
    api_key:
        # Note; this api_key is only valid for relationalai-oss/duckdb-builder.jl; you need
        # to make your own: https://docs.travis-ci.com/user/deployment/releases/
        secure: sL2v5fa8VpgSaBO45IP2zfNkvVgc5yFjR0J2c5K+JwDcPvaGmrFm+AasMXy/TGClOqyX+SqXYowrfH4AQmbyeAxgSLjBsuQL65abE5gfHm6AjGxPu5s480OTIpSlLYl9yobjg+j876cfYziq1R+3FI4tdsd1U5bq97EWTYSnSiP0rPMgk9ldaKGkEfDryCs8CsrO5dTbugpQAmC/Dsgw9wXqLX3wC3CJd63OldEiVAki1XLOIt/ZgcG6aEYd/3qw6bEWvoWSqAj6Fnoed/11eTVNmFPvURn6tGTVniewNX1ERLOZuvn19vzt9gM0IbN1PQ5iHuLt2U6ari2lPtC65YI2bwJ1x8HCDhFr5Y11TWRar8ISOSS+6cYDGqHM6Luch/f4gUcUQFPtQtsK4eyvmmU9FvEpkmZipLfibDfJ7VTCMtp16zgBCUn5ZL6HEviVDUhdT5tlEetiOcLA3aVBRyuQifTN3oJ8ztYCi/o/vtsRUV7a81A5SNX3MOu08lrlYULw98Qnn15p0Dv+4u40EKnXMeT35ZDyAzppvt6V4tIEP/idRAn2ruhQ1pcFsHKQ9SyXnocj/20l+qCGvcCL1kP+rs8PiHiXyI3FOXdB0mzK8lmGf5d3VRHu3Jh/3Zrj9NbabDhcXrn/lYa4hQopZxCZ6iahdnUQvrM5ZJX2qCk=
    file_glob: true
    file: products/*
    skip_cleanup: true
    on:
        repo: RelationalAI-oss/duckdb-builder.jl
        tags: true
