language: julia
os:
- linux
julia:
- 1.2
notifications:
  email: false
git:
  depth: 99999999
  submodules: false
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
before_script:
- julia -e 'using Pkg; Pkg.add("BinaryBuilder")'
script:
- julia build_tarballs.jl --verbose
deploy:
  provider: releases
  api_key:
    secure: G1m7wpQGFTnw9Tj9SZxqq3l2gkbYRnn/kxBUrvtAk6X43r2lxKlWYNDKwbOnQ0PNcghP+etq9Z9iIaQwcmh+rq3fo2yMTBcWYT788g8q1BD7KPFQfpVGyUcTTA5/GJYfe51IyimOVDbBEImQdpNrZFFFqjT4KuCQGbp2brN/9AFlNCnEOEUy7QjivnSMXCLnmv1ZbDGh3nbpNKz7OqePQqEiprkXdcXxuQP+gHm1pGIIpxMQP2CYqy/ODIjydq5gdKgI2RWILqSj/Y+r2UTx2Ugw2VBdAev/T0Eta7AOFyTFhzZ00dwJYLtTLGqAGb8KVic9Kb6DlNV7YTvQfcPjsHFV2xcV5zJKrOWxt1Axg8t7uJMUyoZEdSG1b+fb7xMNqmyAGVlef5O2R0fJ5J6d9jWplhlf/GEKof8mF6R5bXXF1FmtqXkRNVKLdHd6e/U26J9rxPnQqHg9X3nHU0dLGHQjOLBGCPZu/utqRxOrMl3eW64kPpbEHiGZIpns5PxXan6mWfbga648IfUCG6Fn6PfQ2Um6AlHUF1OORO1FERMPURJWyWV3+0gyq91UGRVKvRZoFPJ94rnnHIya+qtKF0DSOEpW7QKUZ1aMXeccps6Z3+kaGIjQKlhJJkYFmTuQ92gyDfBLVOJkczTvkAQ7NheIsl4EQnWZI3dFsE2sK4k=
  file: products/*
  on:
    repo: RelationalAI-oss/duckdb-builder.jl
